name = "ai-portal"
main = "./dist/worker.js"
compatibility_date = "2024-02-24"

# Configure your Pages site
[site]
bucket = "./dist"

# Set environment variables (you'll need to replace these with your actual API keys in the Cloudflare dashboard)
[vars]
VITE_OPENAI_API_KEY = ""
VITE_CLAUDE_API_KEY = ""
VITE_GEMINI_API_KEY = ""

# Configure deployment to Workers
[build]
command = "npm run build"

# Enable static asset hosting for your React app - this handles SPA routing
[site.static]
spa = true